In [40]:
import numpy as np
from numpy import random
import matplotlib.pyplot as plt
from numpy.linalg import svd
from collections import Counter
from scipy.special import softmax
import train_synthetic_nn as tsn
from importlib import reload
reload(tsn)

<module 'train_synthetic_nn' from '/home/siegman/Documents/Shahar/Projects/GreedyInit/train_synthetic_nn.py'>

In [ ]:
def bitarray(num):
    return np.array(map(int,'{:016b}'.format(num)))


In [3]:
a,b = tsn.random_transform_matrix(3)
np.matmul(a,np.diag(b))

array([0.1227887 , 0.00499957, 0.11683207])

In [6]:
a, a_inv = tsn.random_transform_matrix(4)
print(a)
print(a_inv)
print(np.matmul(a,a_inv))
print(np.matmul(a_inv,a))

[[-1.30874251 -0.40815523 -0.31821523  0.11184031]
 [-1.43573995 -0.34589799  0.09638676 -0.14611248]
 [-1.32248743  0.27965241  0.46410316  0.07785045]
 [-0.99012006  0.66754822 -0.33904486 -0.03994149]]
[[-0.04024753 -0.04415306 -0.04067023 -0.03044899]
 [-0.10077133 -0.08540035  0.06904467  0.16481406]
 [-0.14434983  0.04372328  0.21052799 -0.15379864]
 [ 0.538819   -0.70393389  0.37506425 -0.19242826]]
[[2.00000000e-01 1.11022302e-16 4.16333634e-17 3.46944695e-18]
 [1.11022302e-16 2.00000000e-01 4.85722573e-17 2.08166817e-17]
 [5.55111512e-17 4.85722573e-17 2.00000000e-01 8.15320034e-17]
 [1.04083409e-17 1.04083409e-17 6.76542156e-17 2.00000000e-01]]
[[ 2.00000000e-01  6.93889390e-18  1.04083409e-17 -3.46944695e-18]
 [ 1.11022302e-16  2.00000000e-01  1.38777878e-17 -3.46944695e-18]
 [ 8.32667268e-17  4.16333634e-17  2.00000000e-01 -2.60208521e-18]
 [-3.05311332e-16 -1.11022302e-16  0.00000000e+00  2.00000000e-01]]


In [7]:
tsn.fill_uniform_random(5)

(array([[-0.40522219, -0.10144766, -0.46603895, -0.35682277, -0.7486529 ],
        [-0.56046979, -0.28270803, -0.16094759, -0.46722967,  0.88720661],
        [-0.45505685, -0.82162775, -0.16556333,  0.7914599 , -0.17597021],
        [-0.54903736, -0.64450937, -0.6970087 ,  0.41910858,  0.67132069],
        [-0.43239367, -0.64244582,  0.85157969, -0.75797285, -0.41710651],
        [-0.8305639 , -0.66178201,  0.27099683, -0.87533799,  0.93686822],
        [-0.30770671, -0.20670641,  0.20832248,  0.12122112, -0.28389518],
        [-0.30201776, -0.51466412,  0.37457936,  0.43903967,  0.33637402],
        [-0.4990146 ,  0.09728804, -0.62819642, -0.84547255, -0.43261779],
        [-0.07882635,  0.25840851, -0.81370988, -0.63910902,  0.55004161],
        [-0.19768992,  0.15289497, -0.49751331,  0.17901093, -0.72410014],
        [-0.862539  ,  0.18469177, -0.93732717,  0.69449898,  0.86460009],
        [-0.5884407 ,  0.70059188,  0.26536649, -0.839824  , -0.64699394],
        [-0.12337709,  0.

In [8]:
samples,layer2 = tsn.fill_uniform_random(5);
#np.tanh(samples*5)

In [9]:
samples.shape, layer2.shape

((32, 5), (32, 5))

In [10]:
np.argmax(np.matmul(np.tanh(samples*5),layer2.T),axis=1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [ ]:
layer2

In [37]:
a, b,f, b2, c, class_assignments, samples = tsn.generate_layers_and_samples(6,6)

In [21]:

a.shape, b.shape, b2.shape, c.shape, class_assignments.shape, samples.shape

((6, 6), (64, 6), (64,), (6, 64), (64,), (6, 64))

In [23]:
c

array([[0.07692308, 0.07692308, 0.        , 0.07692308, 0.07692308,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.07692308, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.07692308, 0.07692308, 0.07692308,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.07692308, 0.        , 0.        , 0.07692308, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.07692308,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.07692308, 0.        ,
        0.07692308, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.125     , 0.        , 0.        , 0.        , 0. 

In [24]:
b2.shape

(64,)

In [78]:
a, b,f, b2, c, class_assignments, samples = tsn.generate_layers_and_samples(6,12,12422)

In [79]:
net = tsn.network(a, b, f, b2, c)


In [80]:
np.argmax(net(samples),axis=0)==class_assignments

array([ True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [ ]:
# def eval_network(x):
#         x = np.tanh(np.matmul(a,x))
#         x = np.tanh(np.matmul(b,x)+f)
#         x = np.tanh(b2 * x)
#         #x = np.tanh(np.matmul(b2,x))
#         x = softmax(np.matmul(c,x))
#         return x
#     return eval_network


In [ ]:
k = 5
y = net(samples[:,k])
print(y)
print(np.argmax(y))
print(class_assignments[k])

In [ ]:
k = 3
a1 = np.tanh(500*np.matmul(a,samples[:,k]))
print(a1)
a2 = np.tanh(np.matmul(b,a1)-0.25)
print("\na2")
print(np.array2string(a2,precision=3, suppress_small=True))
a2a = np.tanh(a2*18)
print("\na2a")
print(np.array2string(a2a,precision=3, suppress_small=True))
c=bc
c[c==0] = 0
a3 = np.matmul(c,a2a)
print("\na3")
print(np.array2string(a3,precision=4, suppress_small=True))
print()
print(class_assignments[k])

In [ ]:
c

In [ ]:
print(a2[class_assignments==0], sum(a2[class_assignments==0]))
print(a2[class_assignments==5], sum(a2[class_assignments==5]))

In [ ]:
print(a2a[class_assignments==0]+1, np.mean(a2a[class_assignments==0]+1))
print(a2a[class_assignments==5]+1, np.mean(a2a[class_assignments==5]+1))

In [ ]:
print(np.dot(c[0,:],a2))

In [ ]:
print(np.array2string(c,precision=2, suppress_small=True))

In [ ]:
class_assignments[:5]

In [ ]:
c[7,:]

In [ ]:
sum(ct[3,:])

In [ ]:
ct = (1/np.sum(c,axis=1)[:,np.newaxis])*c

In [ ]:

c/np.sum(c,axis=0)

In [ ]:
np.matmul(np.diag(1/np.sum(c,axis=1)),c)