In [112]:
import numpy as np
from numpy import random
import matplotlib.pyplot as plt
from numpy.linalg import svd
from collections import Counter
from scipy.special import softmax

In [22]:
def bitarray(num):
    return np.array(map(int,'{:016b}'.format(num)))

def fill_uniform_random(d):
    # create a D-dimensional hypercube in the range (-1,1) in each axis
    # and place one sample randomly in each bin
    samples = 2**d
    coords = random.rand(samples,d)
    sign_lists= []
    for r in range(d-1,-1,-1):
        sign_lists.append(([0] * 2**r + [1] * 2**r) * 2**(d-r-1))
    
    sign_arr = np.array(sign_lists).T*2-1
    return coords * sign_arr, sign_arr


def orthant_detector_layer(d):
    # create a D-dimensional hypercube in the range (-1,1) in each axis
    # and place one sample randomly in each bin
    sign_lists= []
    for r in range(d-1,-1,-1):
        sign_lists.append(([0] * 2**r + [1] * 2**r) * 2**(d-r-1))
    
    sign_arr = np.array(sign_lists).T*2-1
    return sign_arr



In [169]:
def random_transform_matrix(d):
    u,w,_ = svd(random.rand(d,d))
    return np.matmul(u,np.diag(w)), np.matmul(np.diag(0.2/w),u.T)

In [16]:
a,b=random_transform_matrix(3)
np.matmul(a,np.diag(b))

array([[-0.55198919, -0.58055321, -0.00444318],
       [-1.20311205,  0.15031833,  0.07831523],
       [-0.9448312 ,  0.14776111, -0.09712783]])

In [20]:
a, a_inv = random_transform_matrix(4)
print(a)
print(a_inv)
print(np.matmul(a,a_inv))
print(np.matmul(a_inv,a))

[[-0.70897872 -0.44856906  0.0735389  -0.07829513]
 [-1.52806388  0.20799945 -0.31018044 -0.00583245]
 [-0.9282658   0.66084181  0.23792004 -0.01576273]
 [-1.43657828 -0.42688059  0.13990534  0.05502933]]
[[-0.12302113 -0.2651478  -0.16107156 -0.24927333]
 [-0.51952776  0.24090269  0.76537974 -0.49440842]
 [ 0.4136062  -1.7445535   1.33813803  0.78687214]
 [-8.29324153 -0.61778936 -1.66963332  5.82886226]]
[[ 1.00000000e+00 -2.08166817e-17  1.38777878e-16 -2.77555756e-16]
 [-4.85722573e-17  1.00000000e+00 -3.20923843e-16 -4.85722573e-17]
 [ 8.32667268e-17 -3.76434994e-16  1.00000000e+00 -4.16333634e-17]
 [-1.66533454e-16 -5.55111512e-17  1.38777878e-17  1.00000000e+00]]
[[ 1.00000000e+00  2.77555756e-17 -4.16333634e-17  3.46944695e-18]
 [ 2.22044605e-16  1.00000000e+00  1.52655666e-16  1.38777878e-17]
 [-1.55431223e-15  8.32667268e-16  1.00000000e+00 -4.16333634e-17]
 [ 1.77635684e-15  0.00000000e+00 -8.88178420e-16  1.00000000e+00]]


In [ ]:
fill_uniform_random(5)

In [ ]:
samples,layer2 = fill_uniform_random(5);
#np.tanh(samples*5)

In [ ]:
samples.shape, layer2.shape

In [ ]:
np.argmax(np.matmul(np.tanh(samples*5),layer2.T),axis=1)

In [ ]:
layer2

In [328]:
def create_class_assignments(n_samples, n_class):
    class_assignments = (random.rand(n_samples-n_class)*8).astype(int)
    class_assignments = np.hstack([class_assignments,np.arange(n_class,dtype=int)])
    random.shuffle(class_assignments)
    return class_assignments
    

def network(a, b, f, b2, c):
    def eval_network(x):
        x = np.tanh(np.matmul(a,x))
        x = np.tanh(np.matmul(b,x)+f)
        x = np.tanh(np.matmul(b2,x))
        x = softmax(np.matmul(c,x))
        return x
    return eval_network

def generate_layers_and_samples(n_dims, n_class):
    # x = np.tanh(np.matmul(a,x))
    # 
    random.seed(1234)
    a, a_inv = random_transform_matrix(n_dims)
    b = orthant_detector(n_dims)
    f = -0.25
    n_samples = 2**n_dims
    b2 = np.diag(np.ones(n_samples)) 
    class_assignments = create_class_assignments(n_samples,n_class)    
    c = class_assignment_layer(class_assignments)
    # c = (1/np.sum(c,axis=1)[:,np.newaxis])*c
    samples = random.rand(n_samples, n_dims)
    samples = samples*b
    samples = np.arctanh(samples)
    samples = np.matmul(a_inv, samples.T)
    return a*500, b*0.05, f, b2*18, c, class_assignments, samples
    
def class_assignment_layer(class_assignments):
    # create a layer that produces the maximum value for the correct class
    n_classes = max(class_assignments)+1
    n_samples = len(class_assignments)
    l = np.tile(class_assignments,(n_classes,1)).astype(np.float)
    for i in range(n_classes):
        l[i,:] = l[i,:]== i
    l = (1/np.sum(l,axis=1)[:,np.newaxis])*l   
    #l[l==0] = -0.08
    return l

In [329]:
a, b,f, b2, c, class_assignments, samples = generate_layers_and_samples(6,6)

In [330]:

a.shape, b.shape, b2.shape, c.shape, class_assignments.shape, samples.shape

((6, 6), (64, 6), (64, 64), (8, 64), (64,), (6, 64))

In [331]:
b2

array([[18.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0., 18.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0., 18., ...,  0.,  0.,  0.],
       ...,
       [ 0.,  0.,  0., ..., 18.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0., 18.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0., 18.]])

In [332]:
net = network(a, b, f, b2, c)

In [282]:
s = samples[:,4:7]

In [283]:
class_assignments

array([0, 0, 5, 0, 0, 1, 5, 5, 3, 7, 3, 7, 4, 0, 4, 7, 2, 4, 3, 5, 4, 7,
       6, 5, 3, 4, 1, 0, 1, 0, 3, 7, 7, 3, 2, 3, 4, 1, 7, 7, 0, 1, 5, 1,
       4, 4, 5, 4, 4, 0, 1, 2, 4, 4, 6, 4, 6, 3, 0, 7, 0, 2, 3, 4])

In [340]:
np.argmax(net(samples),axis=0)==class_assignments

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [339]:
k = 5
y = net(samples[:,k])
print(y)
print(np.argmax(y))
print(class_assignments[k])

[0.12502897 0.14453817 0.120338   0.12036946 0.12057214 0.1266293
 0.12034211 0.12218184]
1
1


In [315]:
k = 3
a1 = np.tanh(500*np.matmul(a,samples[:,k]))
print(a1)
a2 = np.tanh(np.matmul(b,a1)-0.25)
print("\na2")
print(np.array2string(a2,precision=3, suppress_small=True))
a2a = np.tanh(a2*18)
print("\na2a")
print(np.array2string(a2a,precision=3, suppress_small=True))
c=bc
c[c==0] = 0
a3 = np.matmul(c,a2a)
print("\na3")
print(np.array2string(a3,precision=4, suppress_small=True))
print()
print(class_assignments[k])

[-1.         -1.         -1.         -0.89083423  1.          1.        ]

a2
[-0.154 -0.055 -0.055  0.045 -0.24  -0.144 -0.144 -0.045 -0.25  -0.154
 -0.154 -0.055 -0.332 -0.24  -0.24  -0.144 -0.25  -0.154 -0.154 -0.055
 -0.332 -0.24  -0.24  -0.144 -0.341 -0.25  -0.25  -0.154 -0.417 -0.332
 -0.332 -0.24  -0.25  -0.154 -0.154 -0.055 -0.332 -0.24  -0.24  -0.144
 -0.341 -0.25  -0.25  -0.154 -0.417 -0.332 -0.332 -0.24  -0.341 -0.25
 -0.25  -0.154 -0.417 -0.332 -0.332 -0.24  -0.426 -0.341 -0.341 -0.25
 -0.496 -0.417 -0.417 -0.332]

a2a
[-0.992 -0.76  -0.76   0.665 -1.    -0.989 -0.989 -0.665 -1.    -0.992
 -0.992 -0.76  -1.    -1.    -1.    -0.989 -1.    -0.992 -0.992 -0.76
 -1.    -1.    -1.    -0.989 -1.    -1.    -1.    -0.992 -1.    -1.
 -1.    -1.    -1.    -0.992 -0.992 -0.76  -1.    -1.    -1.    -0.989
 -1.    -1.    -1.    -0.992 -1.    -1.    -1.    -1.    -1.    -1.
 -1.    -0.992 -1.    -1.    -1.    -1.    -1.    -1.    -1.    -1.
 -1.    -1.    -1.    -1.   ]

a3
[ 0.2063  0.0

In [312]:
c

array([[ 0.09090909,  0.09090909, -0.02      ,  0.09090909,  0.09090909,
        -0.02      , -0.02      , -0.02      , -0.02      , -0.02      ,
        -0.02      , -0.02      , -0.02      ,  0.09090909, -0.02      ,
        -0.02      , -0.02      , -0.02      , -0.02      , -0.02      ,
        -0.02      , -0.02      , -0.02      , -0.02      , -0.02      ,
        -0.02      , -0.02      ,  0.09090909, -0.02      ,  0.09090909,
        -0.02      , -0.02      , -0.02      , -0.02      , -0.02      ,
        -0.02      , -0.02      , -0.02      , -0.02      , -0.02      ,
         0.09090909, -0.02      , -0.02      , -0.02      , -0.02      ,
        -0.02      , -0.02      , -0.02      , -0.02      ,  0.09090909,
        -0.02      , -0.02      , -0.02      , -0.02      , -0.02      ,
        -0.02      , -0.02      , -0.02      ,  0.09090909, -0.02      ,
         0.09090909, -0.02      , -0.02      , -0.02      ],
       [-0.02      , -0.02      , -0.02      , -0.02      , -0.

In [298]:
print(a2[class_assignments==0], sum(a2[class_assignments==0]))
print(a2[class_assignments==5], sum(a2[class_assignments==5]))

[-0.15421794 -0.0554015   0.04451228 -0.23978097 -0.23978097 -0.15421794
 -0.331526   -0.34120732 -0.25004263 -0.34120732 -0.49641817] -2.5592884885900156
[-0.0554015  -0.14354345 -0.04451228 -0.0554015  -0.14354345 -0.25004263
 -0.331526  ] -1.0239708134997196


In [307]:
print(a2a[class_assignments==0]+1, np.mean(a2a[class_assignments==0]+1))
print(a2a[class_assignments==5]+1, np.mean(a2a[class_assignments==5]+1))

[2.34067037e-03 6.90839961e-02 1.87802742e+00 9.40118607e-04
 9.40118607e-04 2.34067037e-03 7.25902075e-04 7.17744415e-04
 8.94081778e-04 7.17744415e-04 6.74520718e-04] 0.1779457265293196
[0.069084   0.00289159 0.12197258 0.069084   0.00289159 0.00089408
 0.0007259 ] 0.038220534451620325


In [248]:
print(np.dot(c[0,:],a2))

0.00742774533213985


In [299]:
print(np.array2string(c,precision=2, suppress_small=True))

[[0.09 0.09 0.   0.09 0.09 0.   0.   0.   0.   0.   0.   0.   0.   0.09
  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.09
  0.   0.09 0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.09 0.
  0.   0.   0.   0.   0.   0.   0.   0.09 0.   0.   0.   0.   0.   0.
  0.   0.   0.09 0.   0.09 0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.14 0.   0.   0.   0.   0.   0.   0.   0.
  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.14 0.
  0.14 0.   0.   0.   0.   0.   0.   0.   0.   0.14 0.   0.   0.   0.14
  0.   0.14 0.   0.   0.   0.   0.   0.   0.14 0.   0.   0.   0.   0.
  0.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
  0.   0.   0.25 0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
  0.   0.   0.   0.   0.   0.   0.25 0.   0.   0.   0.   0.   0.   0.
  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.25 0.   0.   0.   0.
  0.   0.   0.   0.   0.   0.25 0.   0.  ]
 [0.   0.   0.   0.   0. 

In [176]:
class_assignments[:5]

array([5, 1, 7, 3, 3])

In [264]:
c[7,:]

array([-0.05      , -0.05      , -0.05      , -0.05      , -0.05      ,
       -0.05      , -0.05      , -0.05      , -0.05      ,  0.11111111,
       -0.05      ,  0.11111111, -0.05      , -0.05      , -0.05      ,
        0.11111111, -0.05      , -0.05      , -0.05      , -0.05      ,
       -0.05      ,  0.11111111, -0.05      , -0.05      , -0.05      ,
       -0.05      , -0.05      , -0.05      , -0.05      , -0.05      ,
       -0.05      ,  0.11111111,  0.11111111, -0.05      , -0.05      ,
       -0.05      , -0.05      , -0.05      ,  0.11111111,  0.11111111,
       -0.05      , -0.05      , -0.05      , -0.05      , -0.05      ,
       -0.05      , -0.05      , -0.05      , -0.05      , -0.05      ,
       -0.05      , -0.05      , -0.05      , -0.05      , -0.05      ,
       -0.05      , -0.05      , -0.05      , -0.05      ,  0.11111111,
       -0.05      , -0.05      , -0.05      , -0.05      ])

In [189]:
sum(ct[3,:])

1.0000000000000002

In [184]:
ct = (1/np.sum(c,axis=1)[:,np.newaxis])*c

In [161]:

c/np.sum(c,axis=0)

array([[0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1.,
        0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        0., 1., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
        0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
        1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1

In [168]:
np.matmul(np.diag(1/np.sum(c,axis=1)),c)

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.08333333, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.08333333, 0.        ,
        0.08333333, 0.08333333, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.08333333, 0.        ,
        0.        , 0.08333333, 0.        , 0.08333333, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.08333333, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.08333333,
        0.        , 0.        , 0.08333333, 0.08333333, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.08333333, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0. 