In [17]:
import train_synthetic_nn as tsn
import torch
import numpy as np
from importlib import reload
reload(tsn);

In [2]:
a, b, f, b2, c, class_assignments, samples = tsn.generate_layers_and_samples(6, 8, 1234)


In [3]:
net = tsn.Net(6, 8)
net.assign_values_to_layers(a=a, b=b, f=f, b2=b2, c=c)

net_np = tsn.network(a,b,f,b2,c)

attrs updated: {'a', 'f', 'b2', 'c', 'b'}


In [30]:
tensor_samples = torch.Tensor(samples.T)
r = net(tensor_samples).detach().numpy()
ca = np.argmax(r,axis=1)

print(r.shape)

r_np = net_np(samples)

print(r_np.shape)
ca_np = np.argmax(r_np,axis=0)


(64, 8)
(8, 64)


In [31]:
print(class_assignments==ca)

[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True]


In [6]:
print(class_assignments==ca_np)

[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True]


In [ ]:
#     def forward(self, x):
#         x = torch.tanh(self.a(x))
#         x = torch.tanh(self.b(x))
#         x = torch.tanh(x * self.b2 + self.f)
#         x = self.c(x)
#         return x

#     def eval_network(x):
#         x = np.tanh(np.matmul(a,x))
#         x = np.tanh(np.matmul(b,x)+f)
#         x = np.tanh(b2 * x)
#         #x = np.tanh(np.matmul(b2,x))
#         x = softmax(np.matmul(c,x))
#         return x


In [ ]:
x_np = samples[:,13]
x = tensor_samples[13,:]
print(x_np)
print(x)
#np.tanh(np.)

In [ ]:
x1 = torch.tanh(net.a(x))
x1_np = np.tanh(np.matmul(a,x))
print(x)
print(x1)

In [ ]:
x2 = torch.tanh(net.b(x1))
x2_np = np.

In [ ]:
sum(class_assigments==np.argmax(r,axis=1))

In [ ]:
net.a(tensor_samples[0,:])

In [ ]:
np.tanh(np.matmul(a,samples[:,0])/500)

In [ ]:
e = tsn.network(a,b,f,b2,c)

In [ ]:
e(samples[:,0])

In [ ]:
x1 = np.tanh(np.matmul(a,samples[:,0]))
print(x1)

In [ ]:
x2 = np.tanh(np.matmul(b, x1))
print(x2)

In [ ]:
y1 = torch.tanh(net.a(tensor_samples[0,:]))
print(y1)

In [ ]:
y2 = torch.tanh(net.b(y1))
print(y2.detach().numpy())

In [ ]:
y3 = torch.tanh(y2 * net.b2 + net.f)
print(y3)

In [ ]:
x3 = np.tanh(x2 * b2 + f)
print(x3)

In [ ]:
x4 = tsn.softmax(np.matmul(c,x3))
print(x4)

In [ ]:
torch.softmax(net(tensor_samples[0,:]),0)

In [ ]:
class_assigments[0]

In [36]:
type(class_assignments[0])

numpy.int64

In [38]:
trainloader = torch.utils.data.DataLoader(list(zip(tensor_samples, class_assignments)), batch_size=1, shuffle=True, num_workers=0)
    

In [39]:
u=iter(trainloader)

In [40]:
next(u)

[tensor([[-0.0444, -0.0845,  0.0548,  0.4722, -0.9421, -1.9957]]), tensor([4])]

In [44]:
reload(tsn)
nee1 = tsn.main(1234)

attrs updated: {'a', 'f', 'b2', 'c', 'b'}
correct before training: 64
[1, 50] loss: 0.049
[2, 50] loss: 0.046
[3, 50] loss: 0.044
[4, 50] loss: 0.040
[5, 50] loss: 0.039
[6, 50] loss: 0.034
[7, 50] loss: 0.031
[8, 50] loss: 0.030
[9, 50] loss: 0.027
[10, 50] loss: 0.025
[11, 50] loss: 0.024
[12, 50] loss: 0.023
[13, 50] loss: 0.020
[14, 50] loss: 0.020
[15, 50] loss: 0.019
[16, 50] loss: 0.016
[17, 50] loss: 0.016
[18, 50] loss: 0.014
[19, 50] loss: 0.014
[20, 50] loss: 0.013
[21, 50] loss: 0.012
[22, 50] loss: 0.011
[23, 50] loss: 0.010
[24, 50] loss: 0.010
[25, 50] loss: 0.009
[26, 50] loss: 0.009
[27, 50] loss: 0.008
[28, 50] loss: 0.007
[29, 50] loss: 0.007
[30, 50] loss: 0.007
[31, 50] loss: 0.006
[32, 50] loss: 0.006
[33, 50] loss: 0.005
[34, 50] loss: 0.005
[35, 50] loss: 0.005
[36, 50] loss: 0.005
[37, 50] loss: 0.005
[38, 50] loss: 0.004
[39, 50] loss: 0.004
[40, 50] loss: 0.004
[41, 50] loss: 0.004
[42, 50] loss: 0.004
[43, 50] loss: 0.003
[44, 50] loss: 0.004
[45, 50] loss: 

In [50]:
print(net.a.weight)
print(np.array2string(a,precision=3, suppress_small=True))

Parameter containing:
tensor([[-627.0359, -208.7470,  137.0019,  136.2071,   60.5505,   30.8696],
        [-782.6848, -192.2264,  110.7001, -179.8425,  -36.7615,  -21.0204],
        [-611.2431,  -29.0692,  -87.8012,  166.9460,  -95.0105,  -31.9894],
        [-668.6284,   19.2516, -229.1239,  -60.3464,  -37.7940,   49.6865],
        [-762.2719,   83.7010, -148.1664,  -10.6115,  115.8000,  -31.1130],
        [-714.6295,  311.2651,  206.0610,    2.4548,  -19.7765,    9.9728]],
       requires_grad=True)
[[-627.036 -208.748  137.006  136.201   60.56    30.852]
 [-782.685 -192.226  110.7   -179.842  -36.761  -21.02 ]
 [-611.243  -29.068  -87.8    166.945  -95.017  -31.981]
 [-668.628   19.254 -229.124  -60.348  -37.795   49.683]
 [-762.272   83.698 -148.166  -10.615  115.8    -31.123]
 [-714.63   311.265  206.061    2.456  -19.762   10.018]]


In [63]:
print(np.array2string(net.b.weight.detach().numpy().T,precision=2, suppress_small=True))
print()
print(np.array2string(b.T,precision=3, suppress_small=True))

[[-0.07 -0.1  -0.1  -0.07 -0.23 -0.13 -0.24 -0.03 -0.01 -0.02 -0.09 -0.14
  -0.1  -0.1  -0.13  0.   -0.02 -0.06 -0.12 -0.1  -0.15  0.01 -0.19 -0.11
  -0.15 -0.01 -0.07 -0.07 -0.05 -0.13 -0.03  0.05  0.1  -0.01  0.1   0.02
   0.09  0.04  0.13  0.16 -0.03  0.15  0.14  0.19  0.07  0.09  0.09  0.03
   0.16  0.13  0.23  0.12  0.03  0.1   0.02  0.09  0.21  0.16  0.1   0.14
  -0.    0.12  0.01  0.07]
 [-0.15 -0.11 -0.1  -0.07 -0.28 -0.12 -0.06 -0.22 -0.12 -0.12 -0.15 -0.15
  -0.12  0.   -0.03 -0.03  0.08  0.14  0.03  0.11  0.07  0.02  0.09  0.
   0.11  0.19  0.1   0.04  0.13  0.07  0.19  0.07 -0.09 -0.01 -0.09 -0.14
  -0.12  0.06 -0.1  -0.17 -0.16 -0.16 -0.   -0.15 -0.21 -0.05 -0.12 -0.19
   0.17  0.11  0.1   0.12  0.08  0.12  0.07  0.1   0.1   0.08  0.08  0.
   0.08  0.14  0.12  0.04]
 [-0.19 -0.11 -0.1  -0.17 -0.09 -0.13 -0.07 -0.08  0.11  0.12  0.12  0.09
  -0.    0.08  0.03  0.14 -0.1  -0.05 -0.11 -0.12 -0.15 -0.14 -0.19 -0.13
   0.03  0.1   0.08  0.08  0.13  0.05  0.13  0.24 -0.13 -0.11 

In [54]:
print(np.array2string(net.c.weight.detach().numpy(),precision=2, suppress_small=True))
print(np.array2string(c,precision=2, suppress_small=True))

[[ 0.35  0.43  0.42  0.    0.21  0.19 -0.17 -0.22 -0.13 -0.09 -0.14 -0.08
  -0.11  0.39 -0.19  0.04 -0.08 -0.05 -0.    0.06 -0.19 -0.1  -0.26 -0.12
  -0.07  0.21 -0.1   0.25 -0.16  0.31 -0.26  0.3  -0.01  0.01 -0.01 -0.24
   0.37 -0.09  0.31  0.22 -0.12 -0.19 -0.09 -0.19 -0.01 -0.12  0.39 -0.17
  -0.29 -0.02 -0.13 -0.01 -0.07 -0.06  0.02  0.26  0.24 -0.01 -0.04 -0.16
  -0.07 -0.05 -0.15 -0.03]
 [ 0.1  -0.1  -0.11  0.08 -0.12 -0.06 -0.14  0.41 -0.1  -0.1  -0.13 -0.12
  -0.09 -0.08 -0.12 -0.    0.37  0.08 -0.06 -0.11  0.1  -0.17  0.09  0.08
   0.24 -0.06  0.36  0.    0.12 -0.14  0.15 -0.17 -0.07 -0.05 -0.05  0.5
  -0.08 -0.15 -0.05  0.58 -0.13 -0.09 -0.09  0.16  0.    0.04 -0.05  0.45
   0.14 -0.2  -0.14 -0.02  0.   -0.17 -0.09 -0.05  0.04 -0.19 -0.01 -0.06
   0.34  0.12 -0.06  0.02]
 [-0.07 -0.04 -0.04 -0.09  0.29  0.4   0.32  0.2  -0.08 -0.07 -0.06 -0.04
  -0.06 -0.01  0.13 -0.09  0.17  0.15 -0.07 -0.1  -0.11  0.04 -0.01 -0.05
  -0.11  0.11  0.15 -0.03  0.15 -0.04  0.39  0.14  0.03 -0.

In [55]:
print(net.b2)
print(b2)

Parameter containing:
tensor([18.0013, 18.0015, 18.0014, 18.0008, 18.0013, 18.0015, 18.0010, 18.0012,
        18.0018, 18.0013, 18.0020, 18.0010, 18.0016, 18.0017, 18.0010, 18.0006,
        18.0015, 18.0010, 18.0010, 18.0016, 18.0013, 18.0009, 18.0017, 18.0013,
        18.0015, 18.0020, 18.0015, 18.0007, 18.0014, 18.0012, 18.0015, 18.0014,
        18.0013, 18.0018, 18.0015, 18.0007, 18.0015, 18.0011, 18.0010, 18.0023,
        18.0010, 18.0014, 18.0015, 18.0010, 18.0009, 18.0010, 18.0017, 18.0006,
        18.0008, 18.0010, 18.0017, 18.0008, 18.0005, 18.0018, 18.0005, 18.0010,
        18.0019, 18.0011, 18.0008, 18.0012, 18.0011, 18.0013, 18.0021, 18.0012],
       requires_grad=True)
[18. 18. 18. 18. 18. 18. 18. 18. 18. 18. 18. 18. 18. 18. 18. 18. 18. 18.
 18. 18. 18. 18. 18. 18. 18. 18. 18. 18. 18. 18. 18. 18. 18. 18. 18. 18.
 18. 18. 18. 18. 18. 18. 18. 18. 18. 18. 18. 18. 18. 18. 18. 18. 18. 18.
 18. 18. 18. 18. 18. 18. 18. 18. 18. 18.]


In [60]:
print(np.array2string(np.sign(c)*net.c.weight.detach().numpy(),precision=2, suppress_small=True))

[[ 0.35  0.43  0.42  0.    0.    0.   -0.   -0.   -0.   -0.   -0.   -0.
  -0.    0.39 -0.    0.   -0.   -0.   -0.    0.   -0.   -0.   -0.   -0.
  -0.    0.   -0.    0.25 -0.    0.31 -0.    0.   -0.    0.   -0.   -0.
   0.37 -0.    0.31  0.   -0.   -0.   -0.   -0.   -0.   -0.    0.39 -0.
  -0.   -0.   -0.   -0.   -0.   -0.    0.    0.26  0.24 -0.   -0.   -0.
  -0.   -0.   -0.   -0.  ]
 [ 0.   -0.   -0.    0.   -0.   -0.   -0.    0.41 -0.   -0.   -0.   -0.
  -0.   -0.   -0.   -0.    0.37  0.   -0.   -0.    0.   -0.    0.    0.
   0.   -0.    0.36  0.    0.   -0.    0.   -0.   -0.   -0.   -0.    0.5
  -0.   -0.   -0.    0.58 -0.   -0.   -0.    0.    0.    0.   -0.    0.45
   0.   -0.   -0.   -0.    0.   -0.   -0.   -0.    0.   -0.   -0.   -0.
   0.34  0.   -0.    0.  ]
 [-0.   -0.   -0.   -0.    0.    0.4   0.    0.   -0.   -0.   -0.   -0.
  -0.   -0.    0.   -0.    0.    0.   -0.   -0.   -0.    0.   -0.   -0.
  -0.    0.    0.   -0.    0.   -0.    0.39  0.    0.   -0.   -0.   -0.
  -0.  

In [61]:
print(np.array2string((1-np.sign(c))*net.c.weight.detach().numpy(),precision=2, suppress_small=True))

[[ 0.    0.    0.    0.    0.21  0.19 -0.17 -0.22 -0.13 -0.09 -0.14 -0.08
  -0.11  0.   -0.19  0.04 -0.08 -0.05 -0.    0.06 -0.19 -0.1  -0.26 -0.12
  -0.07  0.21 -0.1   0.   -0.16  0.   -0.26  0.3  -0.01  0.01 -0.01 -0.24
   0.   -0.09  0.    0.22 -0.12 -0.19 -0.09 -0.19 -0.01 -0.12  0.   -0.17
  -0.29 -0.02 -0.13 -0.01 -0.07 -0.06  0.02  0.    0.   -0.01 -0.04 -0.16
  -0.07 -0.05 -0.15 -0.03]
 [ 0.1  -0.1  -0.11  0.08 -0.12 -0.06 -0.14  0.   -0.1  -0.1  -0.13 -0.12
  -0.09 -0.08 -0.12 -0.    0.    0.08 -0.06 -0.11  0.1  -0.17  0.09  0.08
   0.24 -0.06  0.    0.    0.12 -0.14  0.15 -0.17 -0.07 -0.05 -0.05  0.
  -0.08 -0.15 -0.05  0.   -0.13 -0.09 -0.09  0.16  0.    0.04 -0.05  0.
   0.14 -0.2  -0.14 -0.02  0.   -0.17 -0.09 -0.05  0.04 -0.19 -0.01 -0.06
   0.    0.12 -0.06  0.02]
 [-0.07 -0.04 -0.04 -0.09  0.29  0.    0.32  0.2  -0.08 -0.07 -0.06 -0.04
  -0.06 -0.01  0.13 -0.09  0.17  0.15 -0.07 -0.1  -0.11  0.04 -0.01 -0.05
  -0.11  0.11  0.15 -0.03  0.15 -0.04  0.    0.14  0.03 -0.08 